Repository Nook-UA/nook_rest_api, pull requests merged in 2024-10, with the labels that each got.

#1 Esnook 25 create the backend repository
  README.md
  requirements.txt
  src/endpoints/README.md
  src/main.py
  src/models/README.md
  src/repositories/README.md
  src/schemas/README.md
Labels: good first issue

#2 Fix requirements
  requirements.txt
Labels: bug

#3 Esnook 36 create an endpoint to get the parks associated to a client
  requirements.txt
  src/endpoints/client.py
  src/endpoints/park.py
  src/main.py
  src/models/client.py
  src/models/park.py
  src/models/utils.py
  src/repositories/__init__.py
  src/schemas/client.py
  src/schemas/park.py
  tests/integration_testing/README.md
  tests/unit_testing/README.md
Labels: enhancement

#5 Documentation api endpoint descriptions
  src/endpoints/authentication.py
  src/endpoints/client.py
  src/endpoints/park.py
Labels: documentation
